### ISSUE TITLE
Team Icy - Discussion

### ISSUE THREAD

**Issue by joker314** [SilversApprentice/ATC-X-Veni-Vidi-Vici#1]
This is a general discussion issue for "Team Icy" in this contest. Saiid, I hope you are alright with this, and everybody in IcyCoder's (@CosmicWebServices) team, feel free to post below.

Good luck to the other teams!

**Comment by joker314** [comment]
Let's obfuscate our algorithms when coding. And how about we perform a diffie hellman key exchange here, so that we can communicate privately?

Also, @BookOwl - in theory, would you mind if we used Haumea for our language (unless you want to :))

**Comment by CosmicWebServices** [comment]
cool

**Comment by BookOwl** [comment]
I wouldn't mind at all. You probably wouldn't like using it though, since it is horrible for obfuscation, has no lists, and barely any string processing functions. XD

**Comment by bwbw223** [comment]
*icy lol

**Comment by SilversApprentice** [comment]
@joker314 yeah, it's fine :P

**Comment by CosmicWebServices** [comment]
Who wants to join?

**Comment by SilversApprentice** [comment]
@bwbw223 lol yeah @BookOwl is on a different team xD

**Comment by bwbw223** [comment]
@SilversApprentice ?

**Comment by bwbw223** [comment]
Oh - BookOwl made Haumea

**Comment by SilversApprentice** [comment]
@bwbw223 ah

**Comment by BookOwl** [comment]
And it stinks. :P

**Comment by SilversApprentice** [comment]
was mistaken then

**Comment by BookOwl** [comment]
???

**Comment by SilversApprentice** [comment]
don't worry about it I was being an idiot

**Comment by SilversApprentice** [comment]
@joker314 feel free to use PigeonScript if you want, btw

**Comment by CosmicWebServices** [comment]
So should we start working now? We are allowed to.

**Comment by CosmicWebServices** [comment]
Uh Oh my job is to make the encrypter... can we use nodejs because I am good at encrypting with nodejs

**Comment by CosmicWebServices** [comment]
@joker314

**Comment by TheUltimatum** [comment]
Oi. @CosmicWebServices That sounds good. I'm going to start cracking at the encrypt1...

**Comment by CosmicWebServices** [comment]
k

**Comment by SilversApprentice** [comment]
You guys can set milestones and such with the sidebar btw

**Comment by CosmicWebServices** [comment]
I know :)

**Comment by CosmicWebServices** [comment]
Guys me and @joker314 are working on the encrypter (guess what this means):
`9998ba1937b2219c1d9b361a599d827229e1db03b769ef828d68d9db09b3cf936ad5a10c2af83a3cf79d4d31e83912dbb76b4346b57ac0d63e178626d1e9a5633a61c5660e570811eafc97e6734651f9865c5cdc7a76e214a7b9a3c585e9a83718fe94d2e3f7306267ff3a90cb67578bfe6b0756183d4b1fe9c63b2f1cd7c231a3e82915df7e4553004dd7d4a7ee749c8f4d7699369620395cee0e2e0ec7a1bab152737971cddcf3dda4e9843c190cc81d8e10`

**Comment by SilversApprentice** [comment]
It means `[INSERT PLAINTEXT HERE]`

**Comment by CosmicWebServices** [comment]
lol not even close

**Comment by SilversApprentice** [comment]
how

**Comment by SilversApprentice** [comment]
just insert your plaintext and it's the exact same

**Comment by CosmicWebServices** [comment]
lol I get it now

**Comment by CosmicWebServices** [comment]
So I noticed that a lot of teams are doing the same (or about) the same thing I am trying to do... I am working on making more unique...

**Comment by CosmicWebServices** [comment]
I am not rewriting it I am just adding on to it

**Comment by TheUltimatum** [comment]
OK...

**Comment by CosmicWebServices** [comment]
lol

**Comment by joker314** [comment]
We need to crack encrypt2 and encrypt1 - let's use Python this time since the other teams have been using JS. We also need to crack *their* encryption and keep our encryption secure.

**Comment by CosmicWebServices** [comment]
@joker314 Should I release our code today? I am going to make the code crazy and hard to read right now... Oh but first I should quickly make the decryption proof

**Comment by joker314** [comment]
How about you try obfuscating it using a tool, and then publish it 10 minutes before the deadline 😜

**Comment by CosmicWebServices** [comment]
1) yes I was planning on doing that
2) Oh come on... ours is already impossible enough.

**Comment by joker314** [comment]
1. Good
2. Well yeah, but let's do it anyway 😝

**Comment by CosmicWebServices** [comment]
1. Good
2. That seems unfair and cheety to me

**Comment by joker314** [comment]
It's not like we are breaking any rules

**Comment by CosmicWebServices** [comment]
True

**Comment by CosmicWebServices** [comment]
Go on gitter I will share you the code before and after obfuscating

**Comment by CosmicWebServices** [comment]
@TheUltimatum and @joker314 how is solution finding going?

**Comment by TheUltimatum** [comment]
So far not very well for me... I'm pretty bad at this sort of thing :(

**Comment by CosmicWebServices** [comment]
aww

**Comment by TheUltimatum** [comment]
Don't know if you'd care. But I'd like to change my hat color to grey.

**Comment by CosmicWebServices** [comment]
What is grey again... Because the encrypter is done @TheUltimatum

**Comment by CosmicWebServices** [comment]
So team... when can you guys work on the decrypter

**Comment by TheUltimatum** [comment]
Sorry... In Disneyland currently with only an iPad it'll be four days before I happen to see a computer.

**Comment by CosmicWebServices** [comment]
K :P

**Comment by CosmicWebServices** [comment]
@joker314 any luck on decryption?

**Comment by algmwc5** [comment]
Yay we cracked yours

**Comment by CosmicWebServices** [comment]
You probebly did not @algmwc5

**Comment by CosmicWebServices** [comment]
@algmwc5 I was correct yours does not work...

**Comment by TheUltimatum** [comment]
@CosmicWebServices his might not work depending on the size of the cipher text.

**Comment by jupiterio** [comment]
@TheUltimatum Actually, ours never works with your current code. Ours requires a password, just like yours uses a random one on the inside. Check out the ATC's topic too see what's wrong.

**Comment by CosmicWebServices** [comment]
Guys if we want to win we have to break the encrypters

**Comment by TheUltimatum** [comment]
I know that... I've barely got time to do things this week though.

**Comment by CosmicWebServices** [comment]
Yeah...............

**Comment by CosmicWebServices** [comment]
I guess I will decrypt...

**Comment by bwbw223** [comment]
IIRC yours is impossible to decrypt

**Comment by joker314** [comment]
You'll just have to wait and see ;)

**Comment by jupiterio** [comment]
@joker314 IIRC Martin already proved it, didn't he?

**Comment by SilversApprentice** [comment]
I believe he did

**Comment by bwbw223** [comment]
Um yours is generating a random password...
